_format_version: "1.1"

services:
  - name: myweb
    url: http://webapi
    routes:
      - name: web-route
        paths:
          - /
  - name: google
    url: https://google.com
    routes:
      - name: google-route
        paths:
          - /google
